# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\资源监视器\cchan.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 621)
        MainWindow.setMinimumSize(QtCore.QSize(433, 621))
        MainWindow.setMaximumSize(QtCore.QSize(433, 621))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 290, 211, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 290, 211, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(20, 50, 111, 111))
        self.label_image.setStyleSheet("image: url(:/newPrefix/icons/cpu.png);\n"
"background-color: rgb(213, 213, 213);")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(150, 50, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(200, 50, 211, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_name.setReadOnly(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_clock = QtWidgets.QLabel(self.centralwidget)
        self.label_clock.setGeometry(QtCore.QRect(150, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_clock.setFont(font)
        self.label_clock.setObjectName("label_clock")
        self.lineEdit_clock = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_clock.setGeometry(QtCore.QRect(240, 80, 171, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_clock.setFont(font)
        self.lineEdit_clock.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_clock.setReadOnly(True)
        self.lineEdit_clock.setObjectName("lineEdit_clock")
        self.label_boost = QtWidgets.QLabel(self.centralwidget)
        self.label_boost.setGeometry(QtCore.QRect(150, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_boost.setFont(font)
        self.label_boost.setObjectName("label_boost")
        self.lineEdit_boost = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_boost.setGeometry(QtCore.QRect(240, 110, 171, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_boost.setFont(font)
        self.lineEdit_boost.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_boost.setReadOnly(True)
        self.lineEdit_boost.setObjectName("lineEdit_boost")
        self.lineEdit_total = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_total.setGeometry(QtCore.QRect(110, 260, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_total.setFont(font)
        self.lineEdit_total.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_total.setReadOnly(True)
        self.lineEdit_total.setObjectName("lineEdit_total")
        self.label_total = QtWidgets.QLabel(self.centralwidget)
        self.label_total.setGeometry(QtCore.QRect(20, 260, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_total.setFont(font)
        self.label_total.setObjectName("label_total")
        self.lineEdit_L2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_L2.setGeometry(QtCore.QRect(190, 260, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_L2.setFont(font)
        self.lineEdit_L2.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_L2.setText("")
        self.lineEdit_L2.setReadOnly(True)
        self.lineEdit_L2.setObjectName("lineEdit_L2")
        self.label_L2 = QtWidgets.QLabel(self.centralwidget)
        self.label_L2.setGeometry(QtCore.QRect(170, 260, 31, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_L2.setFont(font)
        self.label_L2.setObjectName("label_L2")
        self.label_L3 = QtWidgets.QLabel(self.centralwidget)
        self.label_L3.setGeometry(QtCore.QRect(240, 260, 31, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_L3.setFont(font)
        self.label_L3.setObjectName("label_L3")
        self.lineEdit_L3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_L3.setGeometry(QtCore.QRect(260, 260, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_L3.setFont(font)
        self.lineEdit_L3.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_L3.setText("")
        self.lineEdit_L3.setReadOnly(True)
        self.lineEdit_L3.setObjectName("lineEdit_L3")
        self.lineEdit_physical = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_physical.setGeometry(QtCore.QRect(250, 140, 21, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_physical.setFont(font)
        self.lineEdit_physical.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_physical.setReadOnly(True)
        self.lineEdit_physical.setObjectName("lineEdit_physical")
        self.label_physical = QtWidgets.QLabel(self.centralwidget)
        self.label_physical.setGeometry(QtCore.QRect(150, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_physical.setFont(font)
        self.label_physical.setObjectName("label_physical")
        self.label_threadcount = QtWidgets.QLabel(self.centralwidget)
        self.label_threadcount.setGeometry(QtCore.QRect(290, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_threadcount.setFont(font)
        self.label_threadcount.setObjectName("label_threadcount")
        self.lineEdit_threadcount = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_threadcount.setGeometry(QtCore.QRect(390, 140, 21, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_threadcount.setFont(font)
        self.lineEdit_threadcount.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_threadcount.setReadOnly(True)
        self.lineEdit_threadcount.setObjectName("lineEdit_threadcount")
        self.pushButton_min = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_min.setGeometry(QtCore.QRect(370, 10, 21, 21))
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(400, 10, 21, 21))
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.label_VFE = QtWidgets.QLabel(self.centralwidget)
        self.label_VFE.setGeometry(QtCore.QRect(20, 170, 221, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_VFE.setFont(font)
        self.label_VFE.setStatusTip("")
        self.label_VFE.setWhatsThis("")
        self.label_VFE.setObjectName("label_VFE")
        self.lineEdit_VFE = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_VFE.setGeometry(QtCore.QRect(240, 170, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_VFE.setFont(font)
        self.lineEdit_VFE.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_VFE.setReadOnly(True)
        self.lineEdit_VFE.setObjectName("lineEdit_VFE")
        self.lineEdit_VME = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_VME.setGeometry(QtCore.QRect(220, 200, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_VME.setFont(font)
        self.lineEdit_VME.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_VME.setReadOnly(True)
        self.lineEdit_VME.setObjectName("lineEdit_VME")
        self.label_VME = QtWidgets.QLabel(self.centralwidget)
        self.label_VME.setGeometry(QtCore.QRect(20, 200, 201, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_VME.setFont(font)
        self.label_VME.setObjectName("label_VME")
        self.lineEdit_tdp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tdp.setGeometry(QtCore.QRect(370, 170, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lineEdit_tdp.setFont(font)
        self.lineEdit_tdp.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.lineEdit_tdp.setReadOnly(True)
        self.lineEdit_tdp.setObjectName("lineEdit_tdp")
        self.label_threadcount_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_threadcount_2.setGeometry(QtCore.QRect(330, 170, 31, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_threadcount_2.setFont(font)
        self.label_threadcount_2.setObjectName("label_threadcount_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 440, 211, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(210, 440, 211, 171))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "CPU:"))
        self.lineEdit_name.setText(_translate("MainWindow", "Intel(R) Core(TM) i5-7300HQ"))
        self.label_clock.setText(_translate("MainWindow", "Clock:"))
        self.lineEdit_clock.setText(_translate("MainWindow", "@2.5 GHz"))
        self.label_boost.setText(_translate("MainWindow", "Boost Clock:"))
        self.lineEdit_boost.setText(_translate("MainWindow", "@3.3 GHz"))
        self.lineEdit_total.setText(_translate("MainWindow", "100%"))
        self.label_total.setText(_translate("MainWindow", "Total Usage :"))
        self.label_L2.setText(_translate("MainWindow", "L2:"))
        self.label_L3.setText(_translate("MainWindow", "L3:"))
        self.lineEdit_physical.setText(_translate("MainWindow", "4"))
        self.label_physical.setText(_translate("MainWindow", "Physical Cores:"))
        self.label_threadcount.setText(_translate("MainWindow", "ThreadCounts:"))
        self.lineEdit_threadcount.setText(_translate("MainWindow", "4"))
        self.label_VFE.setText(_translate("MainWindow", "VirtualizationFirmwareEnabled:"))
        self.lineEdit_VFE.setText(_translate("MainWindow", "True"))
        self.lineEdit_VME.setText(_translate("MainWindow", "True"))
        self.label_VME.setText(_translate("MainWindow", "VMMonitorModeExtensions:"))
        self.lineEdit_tdp.setText(_translate("MainWindow", "0w"))
        self.label_threadcount_2.setText(_translate("MainWindow", "TDP:"))
        MainWindow.setWindowOpacity(0.92) # 设置窗口透明度
        # MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground) # 设置窗口背景透明
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint) # 隐藏边框
        pe = QPalette()
        MainWindow.setAutoFillBackground(True)
        MainWindow.setPalette(pe)
